services:
  # - name: backend
  #   type: web
  #   env: docker
  #   dockerfilePath: ./backend/Dockerfile # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    # envVars:
    #   - key: DATABASE_USER
    #     value: "sunday"
    #   - key: DATABASE_PASSWORD
    #     value: "123456"
    #   - key: DATABASE_HOST
    #     value: "database"
    #   - key: DATABASE_PORT
    #     value: "27017"
    #   - key: SECRET_KEY
    #     value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
    #   - key: ALGORITHM
    #     value: "HS256"
    #   - key: ACCESS_TOKEN_EXPIRE_MINUTES
    #     value: "30"

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: API_URL
        value: "https://backend-service-url"  # כתובת ה-Backend שמחובר בפריסה ב-Render
