services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    envVars:
      DATABASE_USER: "sunday"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "database"
      DATABASE_PORT: "27017"
      SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    envVars:
      API_URL: "https://<backend-service-url>"  # כתובת ה-Backend שתריץ Render
